language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6

cache:
    - apt

before_install:
 - git submodule --quiet update --init --recursive
 - ./unit-tests/ci/before_install.sh

install:
 - composer --prefer-source install
 - ./install

before_script:
 - export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:"/usr/local/lib"
 - $(phpenv which php) compiler.php generate
 - $(phpenv which php) compiler.php stubs
 - $(phpenv which php) compiler.php api
 - (cd ext; export CFLAGS="-g3 -O1 -fno-delete-null-pointer-checks -Wall -fvisibility=hidden -DZEPHIR_RELEASE=1"; phpize && ./configure --silent --enable-test && make -j2 && sudo make install && phpenv config-add ../unit-tests/ci/test.ini)
 - ulimit -c unlimited || true

script:
 - vendor/bin/phpcs --standard=PSR2 --report=emacs --extensions=php --warning-severity=0 Library/ unit-tests/Extension/ unit-tests/Zephir/
 - valgrind --read-var-info=yes --error-exitcode=1 --fullpath-after= --track-origins=yes --leak-check=full phpunit --debug

after_failure:
 - sudo apt-get -qq install gdb
 - ./unit-tests/ci/after_failure.sh

notifications:
  email:
    - andres@phalconphp.com
    - eduar@phalconphp.com
